print("Welcome to the Band Name Generator.")
City = input("What's the name of the city you grew up in? ")
print(City)
Pet = input("What's your pet's name? ")
print(Pet)
print("Your band name could be " + City + " " + Pet)
